name: web deployment

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: deploy tomcat
      run: |
        cd /home/runner/work/spring3-mvc-maven-xml-hello-world/spring3-mvc-maven-xml-hello-world/target/
        ls  # List files to verify the presence of the WAR file
        curl -v -u : -T spring3-mvc-maven-xml-hello-world-3.0-SNAPSHOT.war 'http://ec2-43.205.206.151.ap-south-1.compute.amazonaws.com:8080/manager/text/deploy?path=/myweb_dev_action&update=true'


    
