name: Web Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build with Maven
      run: mvn clean package

    - name: Print current working directory and list files
      run: |
        pwd
        ls -l

    - name: Deploy to Tomcat
      uses: appleboy/ssh-action@master
      with:
        #host: ${{ secrets.TOMCAT_HOST }}
        username: ${{ secrets.TOMCAT_USERNAME }}
        password: ${{ secrets.TOMCAT_PASSWORD }}
        script: |
          cd /home/runner/work/GitHubActions-WebAppDeployment/GitHubActions-WebAppDeployment/
          ls -l  # List files to verify the presence of the WAR file
          curl -v -u : -T spring3-mvc-maven-xml-hello-world-3.0-SNAPSHOT.war 'http://ec2-43.205.206.151.ap-south-1.compute.amazonaws.com:8080/manager/text/deploy?path=/myweb_dev_action&update=true'
